# Regenerates assets/estate/estate-map.json from cadastre_grid.json, a
# pre-classified 92x92 grid (WATER/BUILDING/LAND/...) extracted from the
# property's cadastral "Plan de Situation" PDF -- see cadastre_grid.json's
# accompanying "meta" block for the pixel<->world (RGF93CC48) transform used
# to build it. Assumes assets/estate/tileset.png already contains the
# compact tile layout referenced below (tid() offsets); that tileset is
# composited by hand from the ChaoticCherryCake source sheet and isn't
# regenerated by this script.
import json
import math
from collections import deque

COLS_SHEET = 8  # compact tileset: 8 cols x 6 rows

def tid(col, row):
    return row * COLS_SHEET + col

GRASS = tid(0, 0)
WATER = tid(1, 0)
POOL = tid(2, 0)
PATH = tid(3, 0)
TENNIS = tid(4, 0)
ROOF_FILL = tid(5, 0)
GRASS_ALT = tid(6, 0)
BUSH_A = tid(7, 0)
BUSH_B = tid(0, 1)
TREE = tid(1, 1)
TREE2 = tid(2, 1)
FLOWER = tid(3, 1)

BUILDING = [[tid(c, 2 + r) for c in range(3)] for r in range(4)]

import os
_HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_HERE, 'cadastre_grid.json')) as f:
    d = json.load(f)
cad = d['grid']
meta = d['meta']
GRID_W, GRID_H = meta['COLS'], meta['ROWS']
XMIN, XMAX, YMIN, YMAX, TILE_M = meta['XMIN'], meta['XMAX'], meta['YMIN'], meta['YMAX'], meta['TILE_M']

def world_to_grid(X, Y):
    return ((X - XMIN) / TILE_M, (YMAX - Y) / TILE_M)

ground = [[GRASS for _ in range(GRID_W)] for _ in range(GRID_H)]
building = [[None for _ in range(GRID_W)] for _ in range(GRID_H)]

def fill(grid, x0, x1, y0, y1, tile):
    for y in range(y0, y1):
        for x in range(x0, x1):
            if 0 <= x < GRID_W and 0 <= y < GRID_H:
                grid[y][x] = tile

def stamp(grid, x0, y0, tiles):
    for ry, row_tiles in enumerate(tiles):
        for rx, t in enumerate(row_tiles):
            if 0 <= y0 + ry < GRID_H and 0 <= x0 + rx < GRID_W:
                grid[y0 + ry][x0 + rx] = t

# --- Water: straight from the cadastral classification (the real river shape) ---
for r in range(GRID_H):
    for c in range(GRID_W):
        if cad[r][c] == 'WATER':
            ground[r][c] = WATER

# --- Buildings: connected-component analysis on the real classified footprints ---
def find_components(target):
    seen = [[False] * GRID_W for _ in range(GRID_H)]
    comps = []
    for r in range(GRID_H):
        for c in range(GRID_W):
            if cad[r][c] == target and not seen[r][c]:
                q = deque([(r, c)])
                seen[r][c] = True
                cells = []
                while q:
                    cr, cc = q.popleft()
                    cells.append((cr, cc))
                    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                        nr, nc = cr + dr, cc + dc
                        if 0 <= nr < GRID_H and 0 <= nc < GRID_W and not seen[nr][nc] and cad[nr][nc] == target:
                            seen[nr][nc] = True
                            q.append((nr, nc))
                comps.append(cells)
    return comps

buildings = find_components('BUILDING')
buildings.sort(key=len, reverse=True)

def centroid(cells):
    rs = sum(c[0] for c in cells) / len(cells)
    cs = sum(c[1] for c in cells) / len(cells)
    return (rs, cs)

def bbox(cells):
    rs = [c[0] for c in cells]; cs = [c[1] for c in cells]
    return (min(rs), max(rs), min(cs), max(cs))

# Fill every real building footprint with the solid roof colour (accurate
# size/shape straight from the cadastral plan) and mark it for collision.
for comp in buildings:
    if len(comp) < 3:
        continue  # tiny noise specks
    for (r, c) in comp:
        ground[r][c] = ROOF_FILL

# The two largest components in the middle of the map (away from the hamlet
# rows at the bottom) are the main house (parcel 56) and the pool house
# (parcel 55); stamp the detailed roof/window sprite on the north edge of
# each for a bit of visual richness on top of the accurate flat footprint.
mid_map_buildings = [comp for comp in buildings if len(comp) >= 15 and bbox(comp)[1] < 65]
mid_map_buildings.sort(key=lambda comp: bbox(comp)[0])  # topmost (northmost) first
for comp in mid_map_buildings[:2]:
    r0, r1, c0, c1 = bbox(comp)
    cc = (c0 + c1) // 2
    stamp(building, max(0, cc - 1), r0, BUILDING)

MAIN_HOUSE = mid_map_buildings[0] if mid_map_buildings else None
POOL_HOUSE = mid_map_buildings[1] if len(mid_map_buildings) > 1 else None

# --- Pool: a small rectangle beside the pool house footprint ---
if POOL_HOUSE:
    r0, r1, c0, c1 = bbox(POOL_HOUSE)
    fill(ground, c1 + 1, c1 + 5, r0 + 1, r0 + 4, POOL)

# --- Tennis court: manually located on the cadastral plan (a dashed
# rectangle that doesn't classify by fill colour), centred in its bbox ---
tc0, tc1 = world_to_grid(1527400, 7228035)
tc2, tc3 = world_to_grid(1527450, 7227994)
tcx = int((tc0 + tc2) / 2); tcy = int((tc1 + tc3) / 2)
fill(ground, tcx - 6, tcx + 6, tcy - 4, tcy + 4, TENNIS)

# --- Driveway: from the south edge (Rue du Prieuré) up to the main house's
# forecourt, routed past the small building near the entrance (likely a
# lodge/gatehouse) rather than in a straight line ---
gatehouse = None
for comp in buildings:
    r0, r1, c0, c1 = bbox(comp)
    if 65 <= r0 <= 78 and c1 < 35:
        gatehouse = comp
        break

if MAIN_HOUSE:
    hr0, hr1, hc0, hc1 = bbox(MAIN_HOUSE)
    house_c = (hc0 + hc1) // 2
    house_south = hr1 + 1
else:
    house_c, house_south = 38, 46

if gatehouse:
    gr0, gr1, gc0, gc1 = bbox(gatehouse)
    gate_c = (gc0 + gc1) // 2
    gate_r = gr0
else:
    gate_c, gate_r = 26, 71

# forecourt in front of the house
fill(ground, house_c - 5, house_c + 5, house_south, house_south + 3, PATH)

# path segment: house forecourt -> gatehouse
steps = max(1, gate_r - house_south)
for i in range(steps + 1):
    t = i / steps
    r = int(house_south + 3 + t * (gate_r - (house_south + 3)))
    c = int(house_c + t * (gate_c - house_c))
    fill(ground, c - 1, c + 2, r, r + 1, PATH)

# path segment: gatehouse -> south edge (Rue du Prieuré)
for r in range(gate_r, GRID_H):
    t = (r - gate_r) / max(1, (GRID_H - 1 - gate_r))
    c = int(gate_c + t * (10))  # drift slightly east toward the road
    fill(ground, c - 1, c + 2, r, r + 1, PATH)

# the public road itself, a band along the south edge
fill(ground, 0, 55, GRID_H - 2, GRID_H, PATH)

# --- Spawn point: south end of the driveway, at the road ---
spawn_tile_x, spawn_tile_y = gate_c + 8, GRID_H - 3
spawn_px = spawn_tile_x * 32 + 16
spawn_py = spawn_tile_y * 32 + 16

# --- Decoration: matched against the aerial photo, which shows dense forest
# on the island AND in a solid wooded band between the river and the house
# (not open field), a mown clearing right around the house/pool, and lighter
# tree cover through the rest of the park. ---
def h(x, y, salt):
    return (x * 92821 + y * 68917 + salt) % 1000

house_r0 = bbox(MAIN_HOUSE)[0] if MAIN_HOUSE else 36

for r in range(GRID_H):
    for c in range(GRID_W):
        if ground[r][c] != GRASS or building[r][c] is not None:
            continue
        # island: enclosed by the river loop, NW area -- dense forest
        is_island_zone = r < 26 and c < 40
        # wooded band between the river and the house's north wall
        is_north_wood = 20 <= r < house_r0 and 20 < c < 65
        # park: east/southeast of the house, away from the driveway/hamlet
        is_park_zone = 20 < r < 70 and c > (house_c + 8 if MAIN_HOUSE else 46)
        # mown clearing immediately around the house/pool/forecourt
        is_clearing = MAIN_HOUSE and (house_c - 11) < c < (house_c + 16) and house_r0 - 3 < r < house_south + 5

        if is_clearing:
            continue
        # h() returns 0-999; these are out of 1000, not 100
        density = 620 if (is_island_zone or is_north_wood) else 260
        if is_island_zone or is_north_wood or is_park_zone:
            v = h(c, r, 7)
            if v < density:
                building[r][c] = TREE if v % 2 == 0 else TREE2
            elif v < density + 120:
                building[r][c] = BUSH_A if v % 2 == 0 else BUSH_B

# --- Garden loop path east of the pool, matching the oval walking path
# visible in the aerial photo ---
if POOL_HOUSE:
    r0, r1, c0, c1 = bbox(POOL_HOUSE)
    loop_cx, loop_cy = c1 + 14, (r0 + r1) // 2
    loop_rx, loop_ry = 10, 7
    for deg in range(0, 360, 3):
        rad = math.radians(deg)
        lc = int(loop_cx + loop_rx * math.cos(rad))
        lr = int(loop_cy + loop_ry * math.sin(rad))
        if 0 <= lr < GRID_H and 0 <= lc < GRID_W and ground[lr][lc] == GRASS:
            ground[lr][lc] = PATH
            building[lr][lc] = None

# hedges bordering the tennis court
for c in range(tcx - 7, tcx + 8):
    for r in (tcy - 5, tcy + 5):
        if 0 <= r < GRID_H and 0 <= c < GRID_W and ground[r][c] == GRASS and building[r][c] is None:
            building[r][c] = BUSH_A if (c % 2 == 0) else BUSH_B

# a couple of flowers by the house forecourt
if MAIN_HOUSE:
    for c in (house_c - 6, house_c + 6):
        r = house_south + 1
        if 0 <= r < GRID_H and 0 <= c < GRID_W and ground[r][c] == GRASS:
            building[r][c] = FLOWER

def flatten(grid):
    data = []
    for row in grid:
        for local_id in row:
            data.append(0 if local_id is None else local_id + 1)
    return data

ground_data = flatten(ground)
building_data = flatten(building)

ground_colliding = {WATER, POOL, ROOF_FILL}
building_colliding = set()
for row_tiles in BUILDING:
    building_colliding.update(row_tiles)

ground_tiles_props = [
    {"id": lid, "properties": [{"name": "collides", "type": "bool", "value": True}]}
    for lid in sorted(ground_colliding)
]
building_tiles_props = [
    {"id": lid, "properties": [{"name": "collides", "type": "bool", "value": True}]}
    for lid in sorted(building_colliding)
    if lid not in ground_colliding
]

tilemap = {
    "compressionlevel": -1,
    "width": GRID_W, "height": GRID_H,
    "tilewidth": 32, "tileheight": 32,
    "infinite": False, "orientation": "orthogonal", "renderorder": "right-down",
    "type": "map", "tiledversion": "1.10.2", "version": "1.10",
    "nextlayerid": 4, "nextobjectid": 2,
    "layers": [
        {"id": 1, "name": "Ground", "type": "tilelayer", "width": GRID_W, "height": GRID_H,
         "x": 0, "y": 0, "opacity": 1, "visible": True, "data": ground_data},
        {"id": 3, "name": "Building", "type": "tilelayer", "width": GRID_W, "height": GRID_H,
         "x": 0, "y": 0, "opacity": 1, "visible": True, "data": building_data},
        {"id": 2, "name": "Objects", "type": "objectgroup", "opacity": 1, "visible": True,
         "x": 0, "y": 0, "objects": [
             {"id": 1, "name": "Spawn Point", "type": "", "x": spawn_px, "y": spawn_py,
              "width": 0, "height": 0, "rotation": 0, "visible": True, "point": True, "properties": []}
         ]},
    ],
    "tilesets": [
        {"firstgid": 1, "name": "estate_tileset", "image": "tileset.png",
         "imagewidth": 256, "imageheight": 192, "tilewidth": 32, "tileheight": 32,
         "columns": 8, "tilecount": 8 * 6, "margin": 0, "spacing": 0,
         "tiles": ground_tiles_props + building_tiles_props}
    ],
}

out_path = "/Users/bill/c-work/mirrorsky/assets/estate/estate-map.json"
with open(out_path, "w") as f:
    json.dump(tilemap, f)

print("wrote", out_path)
print("grid", GRID_W, "x", GRID_H)
print("main house bbox:", bbox(MAIN_HOUSE) if MAIN_HOUSE else None)
print("pool house bbox:", bbox(POOL_HOUSE) if POOL_HOUSE else None)
print("gatehouse:", bbox(gatehouse) if gatehouse else None)
print("spawn px,py =", spawn_px, spawn_py)
print("tennis center grid:", tcx, tcy)
