# Regenerates assets/estate/estate-map.json from cadastre_grid.json, a
# pre-classified 92x92 grid (WATER/BUILDING/LAND/...) extracted from the
# property's cadastral "Plan de Situation" PDF -- see cadastre_grid.json's
# accompanying "meta" block for the pixel<->world (RGF93CC48) transform used
# to build it. Assumes assets/estate/tileset.png already contains the
# compact tile layout referenced below (tid() offsets); that tileset is
# composited by hand from the ChaoticCherryCake source sheet and isn't
# regenerated by this script.
import json
import math
from collections import deque

COLS_SHEET = 8  # compact tileset: 8 cols x 6 rows

def tid(col, row):
    return row * COLS_SHEET + col

GRASS = tid(0, 0)
WATER = tid(1, 0)
POOL = tid(2, 0)
PATH = tid(3, 0)
TENNIS = tid(4, 0)
ROOF_FILL = tid(5, 0)
GRASS_ALT = tid(6, 0)
BUSH_A = tid(7, 0)
BUSH_B = tid(0, 1)
TREE = tid(1, 1)
TREE2 = tid(2, 1)
FLOWER = tid(3, 1)

BUILDING = [[tid(c, 2 + r) for c in range(3)] for r in range(4)]

import os
_HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_HERE, 'cadastre_grid.json')) as f:
    d = json.load(f)
cad = d['grid']
meta = d['meta']
GRID_W, GRID_H = meta['COLS'], meta['ROWS']
XMIN, XMAX, YMIN, YMAX, TILE_M = meta['XMIN'], meta['XMAX'], meta['YMIN'], meta['YMAX'], meta['TILE_M']

# cadastre_grid.json is pre-rotated (see ROTATION_NOTE in its meta) so that the
# house/pool/paths -- which sit at a real ~49 degree angle to true north -- come
# out axis-aligned in this grid, matching the orientation the estate was hand-tiled
# against in map-builder.html. world_to_grid() therefore does the original
# real-world-meters -> unrotated-grid lookup, then applies that same rotation
# (K, Offset, padX/padY, all baked in at grid-generation time) to land in this
# grid's actual coordinate frame.
PAD_X, PAD_Y = meta['padX'], meta['padY']
K = complex(meta['K_re'], meta['K_im'])
OFFSET = complex(meta['Offset_re'], meta['Offset_im'])

def world_to_grid(X, Y):
    old_c, old_r = (X - XMIN) / TILE_M, (YMAX - Y) / TILE_M
    new_g = (complex(old_c, old_r) - OFFSET / 15.5) / K
    return (new_g.real + PAD_X, new_g.imag + PAD_Y)

ground = [[GRASS for _ in range(GRID_W)] for _ in range(GRID_H)]
building = [[None for _ in range(GRID_W)] for _ in range(GRID_H)]

def fill(grid, x0, x1, y0, y1, tile):
    for y in range(y0, y1):
        for x in range(x0, x1):
            if 0 <= x < GRID_W and 0 <= y < GRID_H:
                grid[y][x] = tile

def stamp(grid, x0, y0, tiles):
    for ry, row_tiles in enumerate(tiles):
        for rx, t in enumerate(row_tiles):
            if 0 <= y0 + ry < GRID_H and 0 <= x0 + rx < GRID_W:
                grid[y0 + ry][x0 + rx] = t

# --- Water: straight from the cadastral classification (the real river shape) ---
for r in range(GRID_H):
    for c in range(GRID_W):
        if cad[r][c] == 'WATER':
            ground[r][c] = WATER

# --- Buildings: connected-component analysis on the real classified footprints ---
def find_components(target):
    seen = [[False] * GRID_W for _ in range(GRID_H)]
    comps = []
    for r in range(GRID_H):
        for c in range(GRID_W):
            if cad[r][c] == target and not seen[r][c]:
                q = deque([(r, c)])
                seen[r][c] = True
                cells = []
                while q:
                    cr, cc = q.popleft()
                    cells.append((cr, cc))
                    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                        nr, nc = cr + dr, cc + dc
                        if 0 <= nr < GRID_H and 0 <= nc < GRID_W and not seen[nr][nc] and cad[nr][nc] == target:
                            seen[nr][nc] = True
                            q.append((nr, nc))
                comps.append(cells)
    return comps

buildings = find_components('BUILDING')
buildings.sort(key=len, reverse=True)

def centroid(cells):
    rs = sum(c[0] for c in cells) / len(cells)
    cs = sum(c[1] for c in cells) / len(cells)
    return (rs, cs)

def bbox(cells):
    rs = [c[0] for c in cells]; cs = [c[1] for c in cells]
    return (min(rs), max(rs), min(cs), max(cs))

# Fill every real building footprint with the solid roof colour (accurate
# size/shape straight from the cadastral plan) and mark it for collision.
for comp in buildings:
    if len(comp) < 3:
        continue  # tiny noise specks
    for (r, c) in comp:
        ground[r][c] = ROOF_FILL

# cadastre_grid.json is now rotated to the estate's true orientation rather
# than true north (see world_to_grid() above), so "south"/"north" no longer
# line up with +row/-row the way they used to. Everything below identifies
# the house/pool-house/gatehouse and lays out paths using real spatial
# relationships (distance to water, distance to the house, the direction
# from the house toward the entrance) instead of hardcoded row/col ranges,
# so it stays correct regardless of how the grid is oriented.
water_cells = [(r, c) for r in range(GRID_H) for c in range(GRID_W) if cad[r][c] == 'WATER']

# Multi-source BFS from every water cell gives exact grid-distance to the
# nearest water for every cell in one linear pass (used below for both
# building identification and the "wooded riverbank" decoration density).
dist_to_water = [[None] * GRID_W for _ in range(GRID_H)]
_q = deque()
for (r, c) in water_cells:
    dist_to_water[r][c] = 0
    _q.append((r, c))
while _q:
    r, c = _q.popleft()
    d = dist_to_water[r][c]
    for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
        nr, nc = r + dr, c + dc
        if 0 <= nr < GRID_H and 0 <= nc < GRID_W and dist_to_water[nr][nc] is None:
            dist_to_water[nr][nc] = d + 1
            _q.append((nr, nc))

# The main house and pool house (parcels 56/55) are the two significant
# building footprints closest to the river; the closer of the two -- it
# sits right on the riverbank -- is the main house.
sizable = [comp for comp in buildings if len(comp) >= 15]
sizable.sort(key=lambda comp: min(dist_to_water[r][c] for (r, c) in comp))
MAIN_HOUSE, POOL_HOUSE = (sizable + [None, None])[:2]

for comp in (MAIN_HOUSE, POOL_HOUSE):
    if not comp:
        continue
    r0, r1, c0, c1 = bbox(comp)
    cc = (c0 + c1) // 2
    stamp(building, max(0, cc - 1), r0, BUILDING)

house_cr, house_cc = centroid(MAIN_HOUSE) if MAIN_HOUSE else (GRID_H / 2, GRID_W / 2)

# --- Pool: a small rectangle beside the pool house footprint, offset along
# the pool house's own long axis rather than assuming it's axis-aligned ---
if POOL_HOUSE:
    pr0, pr1, pc0, pc1 = bbox(POOL_HOUSE)
    ph_cr, ph_cc = centroid(POOL_HOUSE)
    # direction away from the main house, through the pool house -- that's
    # the side the pool sits on
    away_r, away_c = ph_cr - house_cr, ph_cc - house_cc
    mag = math.hypot(away_r, away_c) or 1
    away_r, away_c = away_r / mag, away_c / mag
    pool_cr = int(ph_cr + away_r * 6)
    pool_cc = int(ph_cc + away_c * 6)
    pool_c0, pool_c1, pool_r0, pool_r1 = pool_cc - 2, pool_cc + 2, pool_cr - 1, pool_cr + 2
    fill(ground, pool_c0, pool_c1, pool_r0, pool_r1, POOL)
    # a one-tile poolside path all the way round, matching the hand-tiled
    # reference (the automated pool used to be a bare rectangle with nothing
    # around it)
    for r in range(pool_r0 - 1, pool_r1 + 1):
        for c in range(pool_c0 - 1, pool_c1 + 1):
            if not (0 <= r < GRID_H and 0 <= c < GRID_W):
                continue
            if pool_r0 <= r < pool_r1 and pool_c0 <= c < pool_c1:
                continue  # inside the pool itself
            if ground[r][c] == GRASS:
                ground[r][c] = PATH

# --- Tennis court: manually located on the cadastral plan (a dashed
# rectangle that doesn't classify by fill colour), centred in its bbox ---
tc0, tc1 = world_to_grid(1527400, 7228035)
tc2, tc3 = world_to_grid(1527450, 7227994)
tcx = int((tc0 + tc2) / 2); tcy = int((tc1 + tc3) / 2)
fill(ground, tcx - 6, tcx + 6, tcy - 4, tcy + 4, TENNIS)

# --- Driveway: from the road up to the main house's forecourt, routed past
# the small building near the entrance (likely a lodge/gatehouse). The
# gatehouse is simply the nearest other sizable building to the main house --
# a very robust signal regardless of grid orientation. ---
others = [comp for comp in sizable if comp is not MAIN_HOUSE and comp is not POOL_HOUSE]
gatehouse = min(others, key=lambda comp: math.hypot(centroid(comp)[0] - house_cr, centroid(comp)[1] - house_cc)) if others else None

if gatehouse:
    gate_cr, gate_cc = centroid(gatehouse)
else:
    gate_cr, gate_cc = house_cr + 20, house_cc + 15

# Direction from the house toward the entrance/road side -- this replaces
# the old assumption that the road is due south (+row) of the house.
drive_r, drive_c = gate_cr - house_cr, gate_cc - house_cc
_mag = math.hypot(drive_r, drive_c) or 1
drive_r, drive_c = drive_r / _mag, drive_c / _mag

if MAIN_HOUSE:
    hr0, hr1, hc0, hc1 = bbox(MAIN_HOUSE)
    house_edge_r = int(house_cr + drive_r * (hr1 - hr0 + 2) / 2 + drive_r * 2)
    house_edge_c = int(house_cc + drive_c * (hc1 - hc0 + 2) / 2 + drive_c * 2)
else:
    house_edge_r, house_edge_c = int(house_cr), int(house_cc)

def path_strip(cr, cc, half=1):
    fill(ground, int(cc) - half - 1, int(cc) + half + 1, int(cr) - half, int(cr) + half + 1, PATH)

# forecourt immediately in front of the house
path_strip(house_edge_r, house_edge_c, half=2)

# path segment: house forecourt -> gatehouse
steps = max(1, int(_mag))
for i in range(steps + 1):
    t = i / steps
    r = house_edge_r + t * (gate_cr - house_edge_r)
    c = house_edge_c + t * (gate_cc - house_edge_c)
    path_strip(r, c)

# path segment: gatehouse -> map edge in the same direction (representing
# the driveway continuing on to reach the public road)
edge_r, edge_c = gate_cr, gate_cc
for _ in range(int(GRID_W + GRID_H)):
    edge_r += drive_r * 2
    edge_c += drive_c * 2
    if not (0 <= edge_r < GRID_H and 0 <= edge_c < GRID_W):
        break
    path_strip(edge_r, edge_c)

# a stretch of public road around where the driveway meets the grid edge
road_len = 24
perp_r, perp_c = -drive_c, drive_r  # perpendicular to the driveway direction
for i in range(-road_len, road_len):
    r = edge_r + perp_r * i
    c = edge_c + perp_c * i
    path_strip(r, c)

# --- Spawn point: at the road, just off the end of the driveway ---
spawn_tile_x = max(1, min(GRID_W - 2, int(edge_c - drive_c * 3)))
spawn_tile_y = max(1, min(GRID_H - 2, int(edge_r - drive_r * 3)))
spawn_px = spawn_tile_x * 32 + 16
spawn_py = spawn_tile_y * 32 + 16

# --- Decoration: matched against the aerial photo, which shows dense forest
# along the riverbank/island, a mown clearing right around the house/pool,
# and lighter tree cover through the rest of the park. Zones are defined by
# real distance (to water, to the house) rather than row/col ranges, so they
# hold up under any grid rotation. ---
def h(x, y, salt):
    return (x * 92821 + y * 68917 + salt) % 1000

CLEARING_RADIUS = 15
PARK_RADIUS = 48
RIVERBANK_BAND = 6

for r in range(GRID_H):
    for c in range(GRID_W):
        if ground[r][c] != GRASS or building[r][c] is not None:
            continue
        dist_house = math.hypot(r - house_cr, c - house_cc)
        if dist_house < CLEARING_RADIUS:
            continue  # mown clearing right around the house/pool
        is_riverbank = dist_to_water[r][c] is not None and dist_to_water[r][c] <= RIVERBANK_BAND
        is_park_zone = dist_house < PARK_RADIUS
        if not (is_riverbank or is_park_zone):
            continue
        # h() returns 0-999; these are out of 1000, not 100
        density = 620 if is_riverbank else 260
        v = h(c, r, 7)
        if v < density:
            building[r][c] = TREE if v % 2 == 0 else TREE2
        elif v < density + 120:
            building[r][c] = BUSH_A if v % 2 == 0 else BUSH_B

# --- Garden loop path near the pool, matching the oval walking path visible
# in the aerial photo, offset to the park side (away from the main house) ---
if POOL_HOUSE:
    ph_cr, ph_cc = centroid(POOL_HOUSE)
    loop_cr = ph_cr + away_r * 20
    loop_cc = ph_cc + away_c * 20
    loop_rx, loop_ry = 10, 10
    for deg in range(0, 360, 2):
        rad = math.radians(deg)
        lc = int(loop_cc + loop_rx * math.cos(rad))
        lr = int(loop_cr + loop_ry * math.sin(rad))
        if 0 <= lr < GRID_H and 0 <= lc < GRID_W and ground[lr][lc] == GRASS:
            ground[lr][lc] = PATH
            building[lr][lc] = None

# hedges bordering the tennis court
for c in range(tcx - 7, tcx + 8):
    for r in (tcy - 5, tcy + 5):
        if 0 <= r < GRID_H and 0 <= c < GRID_W and ground[r][c] == GRASS and building[r][c] is None:
            building[r][c] = BUSH_A if (c % 2 == 0) else BUSH_B

# a couple of flowers by the house forecourt, either side of the driveway
if MAIN_HOUSE:
    for sign in (-1, 1):
        r = int(house_edge_r + drive_r * 3 + perp_r * 6 * sign)
        c = int(house_edge_c + drive_c * 3 + perp_c * 6 * sign)
        if 0 <= r < GRID_H and 0 <= c < GRID_W and ground[r][c] == GRASS:
            building[r][c] = FLOWER

def flatten(grid):
    data = []
    for row in grid:
        for local_id in row:
            data.append(0 if local_id is None else local_id + 1)
    return data

ground_data = flatten(ground)
building_data = flatten(building)

ground_colliding = {WATER, POOL, ROOF_FILL}
building_colliding = set()
for row_tiles in BUILDING:
    building_colliding.update(row_tiles)

ground_tiles_props = [
    {"id": lid, "properties": [{"name": "collides", "type": "bool", "value": True}]}
    for lid in sorted(ground_colliding)
]
building_tiles_props = [
    {"id": lid, "properties": [{"name": "collides", "type": "bool", "value": True}]}
    for lid in sorted(building_colliding)
    if lid not in ground_colliding
]

tilemap = {
    "compressionlevel": -1,
    "width": GRID_W, "height": GRID_H,
    "tilewidth": 32, "tileheight": 32,
    "infinite": False, "orientation": "orthogonal", "renderorder": "right-down",
    "type": "map", "tiledversion": "1.10.2", "version": "1.10",
    "nextlayerid": 4, "nextobjectid": 2,
    "layers": [
        {"id": 1, "name": "Ground", "type": "tilelayer", "width": GRID_W, "height": GRID_H,
         "x": 0, "y": 0, "opacity": 1, "visible": True, "data": ground_data},
        {"id": 3, "name": "Building", "type": "tilelayer", "width": GRID_W, "height": GRID_H,
         "x": 0, "y": 0, "opacity": 1, "visible": True, "data": building_data},
        {"id": 2, "name": "Objects", "type": "objectgroup", "opacity": 1, "visible": True,
         "x": 0, "y": 0, "objects": [
             {"id": 1, "name": "Spawn Point", "type": "", "x": spawn_px, "y": spawn_py,
              "width": 0, "height": 0, "rotation": 0, "visible": True, "point": True, "properties": []}
         ]},
    ],
    "tilesets": [
        {"firstgid": 1, "name": "estate_tileset", "image": "tileset.png",
         "imagewidth": 256, "imageheight": 192, "tilewidth": 32, "tileheight": 32,
         "columns": 8, "tilecount": 8 * 6, "margin": 0, "spacing": 0,
         "tiles": ground_tiles_props + building_tiles_props}
    ],
}

out_path = "/Users/bill/c-work/mirrorsky/assets/estate/estate-map.json"
with open(out_path, "w") as f:
    json.dump(tilemap, f)

print("wrote", out_path)
print("grid", GRID_W, "x", GRID_H)
print("main house bbox:", bbox(MAIN_HOUSE) if MAIN_HOUSE else None)
print("pool house bbox:", bbox(POOL_HOUSE) if POOL_HOUSE else None)
print("gatehouse:", bbox(gatehouse) if gatehouse else None)
print("spawn px,py =", spawn_px, spawn_py)
print("tennis center grid:", tcx, tcy)
